/* Database schema to keep the structure of entire database. */

-- DAY-1
CREATE TABLE animals(
    id INT GENERATED ALWAYS AS IDENTITY,
    name VARCHAR(100),
    date_of_birth DATE, 
    escape_attempts INT,
    neutered BOOLEAN,
    weight_kg DECIMAL,
    PRIMARY KEY(id)
);

--DAY-2

ALTER TABLE animals
ADD species VARCHAR(50);

--DAY-3

--Create a table named owners with the following columns(id, full_name, age)
-- Create a table named species with the following columns(id, name)
--Modify animals table

DROP TABLE IF EXISTS owners;
DROP TABLE IF EXISTS species;

CREATE TABLE owners(
    id INT GENERATED ALWAYS AS IDENTITY,
    full_name VARCHAR(50),
    age INT,
    PRIMARY KEY(id)
    
);

CREATE TABLE species(
    id INT GENERATED ALWAYS AS IDENTITY,
    name VARCHAR(50), 
    PRIMARY KEY(id)
);

-- Remove column species
ALTER TABLE animals DROP COLUMN species;

-- Add column species_id which is a foreign key referencing species table

ALTER TABLE animals ADD species_id INT;

ALTER TABLE animals
    ADD CONSTRAINT species_id
        FOREIGN KEY (species_id)
            REFERENCES species(id)

;
-- Add column owner_id which is a foreign key referencing the owners table

ALTER TABLE animals ADD owner_id INT;

ALTER TABLE animals
    ADD CONSTRAINT owner_id
        FOREIGN KEY (owner_id)
            REFERENCES owners(id)
;

--DAY-4
--Create a table named vets with the following columns:
CREATE TABLE vets (
    id INT NOT NULL GENERATED BY ALWAYS AS IDENTITY,
    name VARCHAR(100) NOT NULL,
    age INT,
    date_of_graduation DATE,
    PRIMARY KEY (id)
);

-- A many-to-many relationship between the tables species and vets:
CREATE TABLE specializations (
    vet_id INT,
    species_id INT,
    PRIMARY KEY(vet_id, species_id),
    CONSTRAINT fk_vets
      FOREIGN KEY(vet_id) 
	  REFERENCES vets(id),
    CONSTRAINT fk_species
      FOREIGN KEY(species_id) 
	  REFERENCES species(id)
);

-- A many-to-many relationship between the tables animals and vets:
CREATE TABLE visits (
  vet_id INT REFERENCES vets(id),
  animal_id INT REFERENCES animals(id),
  date_of_visit DATE
);

-- DAY-5 (WEEK-2)

-- Add an email column to your owners table
ALTER TABLE owners ADD COLUMN email VARCHAR(120);

-- Creating indexes 
CREATE INDEX visits_animal_id_asc ON visits(animal_id ASC);
CREATE INDEX visits_vet_id_asc ON visits(vet_id ASC);
CREATE INDEX owner_email_asc ON owners(email ASC);